// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_message.proto

#ifndef PROTOBUF_control_5fmessage_2eproto__INCLUDED
#define PROTOBUF_control_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_control_5fmessage_2eproto();
void protobuf_AssignDesc_control_5fmessage_2eproto();
void protobuf_ShutdownFile_control_5fmessage_2eproto();

class PushServiceConfigMsg;

// ===================================================================

class PushServiceConfigMsg : public ::google::protobuf::MessageLite {
 public:
  PushServiceConfigMsg();
  virtual ~PushServiceConfigMsg();

  PushServiceConfigMsg(const PushServiceConfigMsg& from);

  inline PushServiceConfigMsg& operator=(const PushServiceConfigMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const PushServiceConfigMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PushServiceConfigMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PushServiceConfigMsg* other);

  // implements Message ----------------------------------------------

  PushServiceConfigMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PushServiceConfigMsg& from);
  void MergeFrom(const PushServiceConfigMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool fetchBucket = 1;
  inline bool has_fetchbucket() const;
  inline void clear_fetchbucket();
  static const int kFetchBucketFieldNumber = 1;
  inline bool fetchbucket() const;
  inline void set_fetchbucket(bool value);

  // optional bool useBucketV2 = 2;
  inline bool has_usebucketv2() const;
  inline void clear_usebucketv2();
  static const int kUseBucketV2FieldNumber = 2;
  inline bool usebucketv2() const;
  inline void set_usebucketv2(bool value);

  // optional int32 clientVersion = 3;
  inline bool has_clientversion() const;
  inline void clear_clientversion();
  static const int kClientVersionFieldNumber = 3;
  inline ::google::protobuf::int32 clientversion() const;
  inline void set_clientversion(::google::protobuf::int32 value);

  // optional int32 cloudVersion = 4;
  inline bool has_cloudversion() const;
  inline void clear_cloudversion();
  static const int kCloudVersionFieldNumber = 4;
  inline ::google::protobuf::int32 cloudversion() const;
  inline void set_cloudversion(::google::protobuf::int32 value);

  // optional int32 dots = 5;
  inline bool has_dots() const;
  inline void clear_dots();
  static const int kDotsFieldNumber = 5;
  inline ::google::protobuf::int32 dots() const;
  inline void set_dots(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protocol.PushServiceConfigMsg)
 private:
  inline void set_has_fetchbucket();
  inline void clear_has_fetchbucket();
  inline void set_has_usebucketv2();
  inline void clear_has_usebucketv2();
  inline void set_has_clientversion();
  inline void clear_has_clientversion();
  inline void set_has_cloudversion();
  inline void clear_has_cloudversion();
  inline void set_has_dots();
  inline void clear_has_dots();

  bool fetchbucket_;
  bool usebucketv2_;
  ::google::protobuf::int32 clientversion_;
  ::google::protobuf::int32 cloudversion_;
  ::google::protobuf::int32 dots_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_control_5fmessage_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_control_5fmessage_2eproto();
  #endif
  friend void protobuf_AssignDesc_control_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_control_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static PushServiceConfigMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// PushServiceConfigMsg

// optional bool fetchBucket = 1;
inline bool PushServiceConfigMsg::has_fetchbucket() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PushServiceConfigMsg::set_has_fetchbucket() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PushServiceConfigMsg::clear_has_fetchbucket() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PushServiceConfigMsg::clear_fetchbucket() {
  fetchbucket_ = false;
  clear_has_fetchbucket();
}
inline bool PushServiceConfigMsg::fetchbucket() const {
  return fetchbucket_;
}
inline void PushServiceConfigMsg::set_fetchbucket(bool value) {
  set_has_fetchbucket();
  fetchbucket_ = value;
}

// optional bool useBucketV2 = 2;
inline bool PushServiceConfigMsg::has_usebucketv2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PushServiceConfigMsg::set_has_usebucketv2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PushServiceConfigMsg::clear_has_usebucketv2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PushServiceConfigMsg::clear_usebucketv2() {
  usebucketv2_ = false;
  clear_has_usebucketv2();
}
inline bool PushServiceConfigMsg::usebucketv2() const {
  return usebucketv2_;
}
inline void PushServiceConfigMsg::set_usebucketv2(bool value) {
  set_has_usebucketv2();
  usebucketv2_ = value;
}

// optional int32 clientVersion = 3;
inline bool PushServiceConfigMsg::has_clientversion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PushServiceConfigMsg::set_has_clientversion() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PushServiceConfigMsg::clear_has_clientversion() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PushServiceConfigMsg::clear_clientversion() {
  clientversion_ = 0;
  clear_has_clientversion();
}
inline ::google::protobuf::int32 PushServiceConfigMsg::clientversion() const {
  return clientversion_;
}
inline void PushServiceConfigMsg::set_clientversion(::google::protobuf::int32 value) {
  set_has_clientversion();
  clientversion_ = value;
}

// optional int32 cloudVersion = 4;
inline bool PushServiceConfigMsg::has_cloudversion() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PushServiceConfigMsg::set_has_cloudversion() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PushServiceConfigMsg::clear_has_cloudversion() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PushServiceConfigMsg::clear_cloudversion() {
  cloudversion_ = 0;
  clear_has_cloudversion();
}
inline ::google::protobuf::int32 PushServiceConfigMsg::cloudversion() const {
  return cloudversion_;
}
inline void PushServiceConfigMsg::set_cloudversion(::google::protobuf::int32 value) {
  set_has_cloudversion();
  cloudversion_ = value;
}

// optional int32 dots = 5;
inline bool PushServiceConfigMsg::has_dots() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PushServiceConfigMsg::set_has_dots() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PushServiceConfigMsg::clear_has_dots() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PushServiceConfigMsg::clear_dots() {
  dots_ = 0;
  clear_has_dots();
}
inline ::google::protobuf::int32 PushServiceConfigMsg::dots() const {
  return dots_;
}
inline void PushServiceConfigMsg::set_dots(::google::protobuf::int32 value) {
  set_has_dots();
  dots_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_control_5fmessage_2eproto__INCLUDED
