#ifndef MIMC_CPP_SDK_ERROR_H
#define MIMC_CPP_SDK_ERROR_H

const char* const DIAL_CALL_TIMEOUT = "DIAL_CALL_TIMEOUT";
const char* const INVITE_RESPONSE_TIMEOUT = "INVITE_RESPONSE_TIMEOUT";
const char* const CREATE_RELAY_TIMEOUT = "CREATE_RELAY_TIMEOUT";
const char* const CLOSE_CALL_TIMEOUT = "CLOSE_CALL_TIMEOUT";
const char* const UPDATE_TIMEOUT = "UPDATE_TIMEOUT";
const char* const COMMON_TIMEOUT = "TIMEOUT";

const char* const SEND_BIND_RELAY_REQUEST_FAIL = "SEND_BIND_RELAY_REQUEST_FAIL";
const char* const CREATE_RELAY_CONN_FAIL = "CREATE_RELAY_CONN_FAIL";

#endif