// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging-protobuf/xiaomi-protobuf-messaging/src/main/proto/control_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include <mimc/control_message.pb.h>

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {

namespace {

const ::google::protobuf::Descriptor* PushServiceConfigMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PushServiceConfigMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto() {
  protobuf_AddDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "messaging-protobuf/xiaomi-protobuf-messaging/src/main/proto/control_message.proto");
  GOOGLE_CHECK(file != NULL);
  PushServiceConfigMsg_descriptor_ = file->message_type(0);
  static const int PushServiceConfigMsg_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, fetchbucket_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, usebucketv2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, clientversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, cloudversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, dots_),
  };
  PushServiceConfigMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PushServiceConfigMsg_descriptor_,
      PushServiceConfigMsg::default_instance_,
      PushServiceConfigMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PushServiceConfigMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PushServiceConfigMsg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PushServiceConfigMsg_descriptor_, &PushServiceConfigMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto() {
  delete PushServiceConfigMsg::default_instance_;
  delete PushServiceConfigMsg_reflection_;
}

void protobuf_AddDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\nQmessaging-protobuf/xiaomi-protobuf-mes"
    "saging/src/main/proto/control_message.pr"
    "oto\022\010protocol\"{\n\024PushServiceConfigMsg\022\023\n"
    "\013fetchBucket\030\001 \001(\010\022\023\n\013useBucketV2\030\002 \001(\010\022"
    "\025\n\rclientVersion\030\003 \001(\005\022\024\n\014cloudVersion\030\004"
    " \001(\005\022\014\n\004dots\030\005 \001(\005", 218);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messaging-protobuf/xiaomi-protobuf-messaging/src/main/proto/control_message.proto", &protobuf_RegisterTypes);
  PushServiceConfigMsg::default_instance_ = new PushServiceConfigMsg();
  PushServiceConfigMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto {
  StaticDescriptorInitializer_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto() {
    protobuf_AddDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto();
  }
} static_descriptor_initializer_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PushServiceConfigMsg::kFetchBucketFieldNumber;
const int PushServiceConfigMsg::kUseBucketV2FieldNumber;
const int PushServiceConfigMsg::kClientVersionFieldNumber;
const int PushServiceConfigMsg::kCloudVersionFieldNumber;
const int PushServiceConfigMsg::kDotsFieldNumber;
#endif  // !_MSC_VER

PushServiceConfigMsg::PushServiceConfigMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PushServiceConfigMsg::InitAsDefaultInstance() {
}

PushServiceConfigMsg::PushServiceConfigMsg(const PushServiceConfigMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PushServiceConfigMsg::SharedCtor() {
  _cached_size_ = 0;
  fetchbucket_ = false;
  usebucketv2_ = false;
  clientversion_ = 0;
  cloudversion_ = 0;
  dots_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PushServiceConfigMsg::~PushServiceConfigMsg() {
  SharedDtor();
}

void PushServiceConfigMsg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PushServiceConfigMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PushServiceConfigMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PushServiceConfigMsg_descriptor_;
}

const PushServiceConfigMsg& PushServiceConfigMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_messaging_2dprotobuf_2fxiaomi_2dprotobuf_2dmessaging_2fsrc_2fmain_2fproto_2fcontrol_5fmessage_2eproto();
  return *default_instance_;
}

PushServiceConfigMsg* PushServiceConfigMsg::default_instance_ = NULL;

PushServiceConfigMsg* PushServiceConfigMsg::New() const {
  return new PushServiceConfigMsg;
}

void PushServiceConfigMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    fetchbucket_ = false;
    usebucketv2_ = false;
    clientversion_ = 0;
    cloudversion_ = 0;
    dots_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PushServiceConfigMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool fetchBucket = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fetchbucket_)));
          set_has_fetchbucket();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_useBucketV2;
        break;
      }

      // optional bool useBucketV2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_useBucketV2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &usebucketv2_)));
          set_has_usebucketv2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_clientVersion;
        break;
      }

      // optional int32 clientVersion = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_clientVersion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &clientversion_)));
          set_has_clientversion();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_cloudVersion;
        break;
      }

      // optional int32 cloudVersion = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cloudVersion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cloudversion_)));
          set_has_cloudversion();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_dots;
        break;
      }

      // optional int32 dots = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dots:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dots_)));
          set_has_dots();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PushServiceConfigMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool fetchBucket = 1;
  if (has_fetchbucket()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->fetchbucket(), output);
  }

  // optional bool useBucketV2 = 2;
  if (has_usebucketv2()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->usebucketv2(), output);
  }

  // optional int32 clientVersion = 3;
  if (has_clientversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->clientversion(), output);
  }

  // optional int32 cloudVersion = 4;
  if (has_cloudversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->cloudversion(), output);
  }

  // optional int32 dots = 5;
  if (has_dots()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->dots(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PushServiceConfigMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool fetchBucket = 1;
  if (has_fetchbucket()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->fetchbucket(), target);
  }

  // optional bool useBucketV2 = 2;
  if (has_usebucketv2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->usebucketv2(), target);
  }

  // optional int32 clientVersion = 3;
  if (has_clientversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->clientversion(), target);
  }

  // optional int32 cloudVersion = 4;
  if (has_cloudversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->cloudversion(), target);
  }

  // optional int32 dots = 5;
  if (has_dots()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->dots(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PushServiceConfigMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool fetchBucket = 1;
    if (has_fetchbucket()) {
      total_size += 1 + 1;
    }

    // optional bool useBucketV2 = 2;
    if (has_usebucketv2()) {
      total_size += 1 + 1;
    }

    // optional int32 clientVersion = 3;
    if (has_clientversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->clientversion());
    }

    // optional int32 cloudVersion = 4;
    if (has_cloudversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cloudversion());
    }

    // optional int32 dots = 5;
    if (has_dots()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->dots());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PushServiceConfigMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PushServiceConfigMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PushServiceConfigMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PushServiceConfigMsg::MergeFrom(const PushServiceConfigMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_fetchbucket()) {
      set_fetchbucket(from.fetchbucket());
    }
    if (from.has_usebucketv2()) {
      set_usebucketv2(from.usebucketv2());
    }
    if (from.has_clientversion()) {
      set_clientversion(from.clientversion());
    }
    if (from.has_cloudversion()) {
      set_cloudversion(from.cloudversion());
    }
    if (from.has_dots()) {
      set_dots(from.dots());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PushServiceConfigMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PushServiceConfigMsg::CopyFrom(const PushServiceConfigMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushServiceConfigMsg::IsInitialized() const {

  return true;
}

void PushServiceConfigMsg::Swap(PushServiceConfigMsg* other) {
  if (other != this) {
    std::swap(fetchbucket_, other->fetchbucket_);
    std::swap(usebucketv2_, other->usebucketv2_);
    std::swap(clientversion_, other->clientversion_);
    std::swap(cloudversion_, other->cloudversion_);
    std::swap(dots_, other->dots_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PushServiceConfigMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PushServiceConfigMsg_descriptor_;
  metadata.reflection = PushServiceConfigMsg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)
